### ISSUE TITLE
it lint other files that are not eslint configs

### ISSUE THREAD

**Issue by JusttCallMeMike** [ghmcadams/vscode-lintlens#70]
it shows tons of errors in my ".putout.json"
but it is not a eslint config 

you probably should change activation event or add config to regext config file path  to include / ignore

**Comment by ghmcadams** [comment]
Thanks @JusttCallMeMike.  I originally activated this extension only when the filename matched one of the more common variants of an eslint config file, but had recently expanded it to support any file name (among other reasons, to support shared configs like the one from the airbnb style guide).  I do not wish to revert to the previously limiting support model, but I will (for now) add `.putout.json` to a block-list.

Thanks for letting me know of this issue.  I will have a fix released soon.

**Comment by ghmcadams** [comment]
I just released a new version that should take care of this issue.  Please let me know if it is not resolved.

**Comment by omnichronous** [comment]
I'm also getting errors in my `.commitlintrc.js`. Maybe we could get a setting like in ErrorLens so we can manage our own exclusions?

```
"lintLens.excludePatterns": [
    ".commitlintrc.js"
],
```

**Comment by philsherry** [comment]
☝🏻 That would be a good solution, if nothing else solves it. I'm still getting this in my `.yamllint.yaml` files. 

<img width="816" alt="lintlens-vs-yamllint" src="https://github.com/ghmcadams/vscode-lintlens/assets/272769/b68c45dc-7a17-4dfe-9892-1f95ababee08">
